bilyeo/urls.py
from django.urls import path

from .views import StuffList, RentalList, StuffDetailView, RentalDetailView, StuffCreateView, \
    MyRentalListView, MyStuffListView, index, categories_posts, StuffUpdateView, StuffDeleteView, RentalDeleteView, \
    RentalUpdateView, RequestRentalList

app_name = 'bilyeo'

urlpatterns = [
    path('', index, name='index'),
    path('stuff_list/', StuffList.as_view(), name='stuff_list'),
    path('stuff/create/', StuffCreateView.as_view(), name='stuff_create'),
    path('stuff/<int:pk>/', StuffDetailView.as_view(), name='stuff_detail'),
    path('stuff/<int:pk>/update/', StuffUpdateView.as_view(), name='stuff_update'),
    path('stuff/<int:pk>/delete/', StuffDeleteView, name='stuff_delete'),
    path('stuff/category/<str:slug>/', categories_posts, name='category_list'),
    path('rental/<int:pk>/', RentalDetailView.as_view(), name='rental_detail'),
    path('rental/<int:pk>/delete/', RentalDeleteView, name='rental_delete'),
    path('rental/<int:pk>/update/', RentalUpdateView.as_view(), name='rental_update'),
    path('rental_list/', RentalList.as_view(), name='rental_list'),
    path('request_list/', RequestRentalList.as_view(), name='request_list'),
    path('my_rental_list/', MyRentalListView.as_view(), name='my_rental_list'),
    path('my_stuff_list/', MyStuffListView.as_view(), name='my_stuff_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bilyeo.urls')),
    path('account/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('google/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bilyeo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, default='no-category')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/stuff/category/{self.slug}'

    class Meta:
        verbose_name_plural : 'Categories'

class Stuff(models.Model):
    name = models.CharField(max_length=50, null=False, verbose_name='제품명')
    image = models.ImageField(upload_to='stuff/images/%Y/%m/%d/', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자')
    fee = models.IntegerField(verbose_name='대여료')
    desc = models.CharField(max_length=500, verbose_name='설명')

    STUFF_STATUS = (
        ('a', 'available'),
        ('u', 'unavailable'),
    )

    status = models.CharField(
        max_length = 1,
        choices = STUFF_STATUS,
        blank = True,
        default = 'a',
        help_text = 'Stuff availability',
    )

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='작성일')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정일')

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk}] {self.author}님께서 등록하신 물건 <{self.name}>'

    def get_absolute_url(self):
        return f'/stuff/{self.pk}/'

class Rental(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='대여자')
    stuff = models.ForeignKey(Stuff, on_delete=models.CASCADE, verbose_name='제품')
    rental_date = models.DateTimeField(verbose_name='대여일')
    return_date = models.DateTimeField(verbose_name='반납일')
    total_fee = models.IntegerField(verbose_name='대여료 총액')

    RENTAL_STATUS = (
        ('d', 'Default'),
        ('r', 'Request'),
        ('a', 'Accept'),
        ('c', 'Completed'),
    )

    status = models.CharField(
        max_length = 1,
        choices = RENTAL_STATUS,
        blank = True,
        default = 'd',
        help_text = 'Rental availability',
    )

    def __str__(self):
        return f'{self.user}님께서 {self.rental_date}부터 {self.return_date}까지 대여한 <{self.stuff.name}>'

bilyeo/forms.py
from django import forms

from bilyeo.models import Category

class StuffForm(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    fee = forms.IntegerField(required=True)
    image = forms.ImageField(required=True)
    STUFF_STATUS = (
        ('a', 'available'),
        ('u', 'unavailable'),
    )
    status = forms.ChoiceField(choices=STUFF_STATUS, required=True)
    desc = forms.CharField(widget=forms.Textarea(), required=True)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False)

class AvailabilityForm(forms.Form):
    rental_date = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])
    return_date = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])

class AcceptForm(forms.Form):
    RENTAL_STATUS = (
        ('d', 'Default'),
        ('r', 'Request'),
        ('a', 'Accept'),
        ('c', 'Completed'),
    )
    status = forms.ChoiceField(choices=RENTAL_STATUS, required=True)

bilyeo/views.py
from pyexpat.errors import messages

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, View
from bilyeo.models import Stuff, Rental, Category
from bilyeo.forms import AvailabilityForm, AcceptForm, StuffForm
from bilyeo.rental_functions.cal_rental_fee import find_total_rental_fee
from bilyeo.rental_functions.availability import check_availability
from django.contrib.auth.models import User

def index(request):
    stuff_list = Stuff.objects.all()
    category_list = Category.objects.all()

    context = {
        'stuff_list': stuff_list,
        'category_list': category_list,
    }
    return render(request, 'bilyeo/index.html', context)

@method_decorator(login_required, name="dispatch")
class StuffCreateView(View):
    def get(self, request, *args, **kwargs):
        category_list = Category.objects.all()
        form = StuffForm()
        context = {
            'form': form,
            'category_list': category_list,
        }
        return render(request, 'bilyeo/stuff_create.html', context)

    def post(self, request, *args, **kwargs):
        form = StuffForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            stuff = Stuff.objects.create(
                author=self.request.user,
                name=data['name'],
                image=data['image'],
                desc=data['desc'],
                status=data['status'],
                category=data['category'],
                fee = data['fee'],
            )
            stuff.save()
            return redirect('bilyeo:stuff_detail', pk=stuff.pk)
        else:
            return HttpResponse(
                "<script>alert('해당 물품을 등록할 수 없습니다. 유효한 입력으로 시도해주세요. :)');location.href='/stuff_list/';</script>")
        return HttpResponse(
            "<script>alert('유효하지 않은 전송입니다. :(');location.href='/stuff_list/';</script>")

class StuffList(ListView):
    model = Stuff

    def get_context_data(self, **kwargs):
        context = super(StuffList, self).get_context_data()
        context['category_list'] = Category.objects.all()
        return context

@method_decorator(login_required, name="dispatch")
class StuffDetailView(View):
    def get(self, request, *args, **kwargs):
        stuff = get_object_or_404(Stuff, pk=self.kwargs['pk'])
        form = AvailabilityForm()
        category_list = Category.objects.all()

        if stuff.author == self.request.user:
            context = {
                'stuff': stuff,
                'form': form,
                'category_list': category_list,
            }

        else:
            context = {
                'stuff': stuff,
                'form': form,
                'category_list': category_list,
            }
        return render(request, 'bilyeo/stuff_detail.html', context)

    def post(self, request, *args, **kwargs):
        stuff = get_object_or_404(Stuff, pk=self.kwargs['pk'])
        form = AvailabilityForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            if check_availability(stuff, data['rental_date'], data['return_date']):
                total_fee = find_total_rental_fee(data['rental_date'], data['return_date'], kwargs.get("pk"))
                rental = Rental.objects.create(
                    user=self.request.user,
                    stuff=stuff,
                    status='r',
                    rental_date=data['rental_date'],
                    return_date=data['return_date'],
                    total_fee = total_fee,
                )
                rental.save()
                return redirect('bilyeo:rental_detail', pk=rental.pk)
            else:
                return HttpResponse(
                    "<script>alert('해당 물품은 이미 예약되었습니다! 다른 물품으로 시도해주세요. :)');location.href='/stuff_list/';</script>")

        return HttpResponse(
            "<script>alert('유효하지 않은 전송입니다. :(');location.href='/stuff_list/';</script>")


@method_decorator(login_required, name="dispatch")
class StuffUpdateView(View):
    def get(self, request, *args, **kwargs):
        category_list = Category.objects.all()
        form = StuffForm()
        context = {
            'form': form,
            'category_list': category_list,
        }
        return render(request, 'bilyeo/stuff_update.html', context)

    def post(self, request, *args, **kwargs):
        stuff = get_object_or_404(Stuff, pk=self.kwargs['pk'])
        form = StuffForm(request.POST, request.FILES)
        if form.is_valid() and stuff.author == self.request.user:
            data = form.cleaned_data

            category = data['category']
            if category == None:
                stuff.category = None
            else:
                stuff.category = Category.objects.get(name=category)

            stuff.name = data['name']
            stuff.image = data['image']
            stuff.desc = data['desc']
            stuff.status = data['status']
            stuff.fee = data['fee']

            stuff.save()
            return redirect('bilyeo:stuff_detail', pk=stuff.pk)
        else:
            return HttpResponse(
                "<script>alert('해당 물품을 변경할 수 없습니다. 유효한 입력으로 시도해주세요. :)');location.href='/stuff_list/';</script>")
        return HttpResponse(
            "<script>alert('유효하지 않은 전송입니다. :(');location.href='/stuff_list/';</script>")

@login_required
def StuffDeleteView(request, pk):
    stuff = get_object_or_404(Stuff, pk=pk)

    if stuff.author != request.user:
        return HttpResponse(
                "<script>alert('작성자만 삭제 가능합니다. :(');location.href='/stuff_list/';</script>")
    else:
        stuff.delete()
        return redirect('bilyeo:stuff_list')

    return HttpResponse(
            "<script>alert('해당 물품을 삭제할 수 없습니다. 유효한 입력으로 시도해주세요. :(');location.href='/stuff_list/';</script>")

@method_decorator(login_required, name="dispatch")
class RentalDetailView(View):
    def get(self, request, *args, **kwargs):
        rental = get_object_or_404(Rental, pk=self.kwargs['pk'])
        form = AcceptForm()
        category_list = Category.objects.all()

        context = {
            'rental': rental,
            'form': form,
            'category_list': category_list,
        }
        return render(request, 'bilyeo/rental_detail.html', context)

    def post(self, request, *args, **kwargs):
        rental = get_object_or_404(Rental, pk=self.kwargs['pk'])
        form = AcceptForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            rental.user = rental.user
            rental.stuff = rental.stuff
            rental.status = data['status']
            rental.rental_date = rental.rental_date
            rental.return_date = rental.return_date
            rental.save()
            return redirect('bilyeo:rental_detail', pk=rental.pk)
        else:
            return HttpResponse(
                "<script>alert('상태 변경에 실패했습니다! 유효한 입력으로 시도해주세요. :)');location.href='/rental/'" + rental.pk + ";</script>")
        return HttpResponse(
            "<script>alert('상태 변경에 실패했습니다! 유효한 입력으로 시도해주세요. :)');location.href='/rental/'" + rental.pk + ";</script>")

@method_decorator(login_required, name="dispatch")
class RentalUpdateView(View):
    def get(self, request, *args, **kwargs):
        category_list = Category.objects.all()
        form = AvailabilityForm()
        context = {
            'form': form,
            'category_list': category_list,
        }
        return render(request, 'bilyeo/stuff_update.html', context)

    def post(self, request, *args, **kwargs):
        rental = get_object_or_404(Rental, pk=self.kwargs['pk'])
        form = AvailabilityForm(request.POST, request.FILES)
        if form.is_valid() and rental.stuff.author == self.request.user:
            data = form.cleaned_data

            if check_availability(rental.stuff, data['rental_date'], data['return_date']):
                total_fee = find_total_rental_fee(data['rental_date'], data['return_date'], rental.stuff.pk)

                rental.rental_date = data['rental_date']
                rental.return_date = data['return_date']
                rental.total_fee = total_fee

                rental.save()
                return redirect('bilyeo:rental_detail', pk=rental.pk)
        else:
            return HttpResponse(
                "<script>alert('해당 대여를 변경할 수 없습니다! 유효한 입력으로 시도해주세요. :)');location.href='/rental/'" + rental.pk + ";</script>")
        return HttpResponse(
            "<script>alert('유효하지 않은 전송입니다. :(');location.href='/stuff_list/';</script>")


@login_required
def RentalDeleteView(request, pk):
    rental = get_object_or_404(Rental, pk=pk)

    if rental.user != request.user:
        return HttpResponse(
                "<script>alert('작성자만 삭제 가능합니다. :(');location.href='/stuff_list/';</script>")
    else:
        rental.delete()
        return redirect('bilyeo:my_rental_list')

    return HttpResponse(
            "<script>alert('해당 대여를 삭제할 수 없습니다. 유효한 입력으로 시도해주세요. :(');location.href='/stuff_list/';</script>")

@method_decorator(login_required, name="dispatch")
class MyRentalListView(View):
    def get(self, request, *args, **kwargs):
        user = self.request.user
        my_rental_list = Rental.objects.filter(user=user)
        category_list = Category.objects.all()

        context = {
            'my_rental_list': my_rental_list,
            'category_list': category_list,
        }
        return render(request, 'bilyeo/my_rental_list.html', context)

@method_decorator(login_required, name="dispatch")
class MyStuffListView(View):
    def get(self, request, *args, **kwargs):
        user = self.request.user
        my_stuff_list = Stuff.objects.filter(author__username=user.username)
        category_list = Category.objects.all()
        context = {

bilyeo/templates/bilyeo/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Jua&family=Poor+Story&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" >
    <link rel="stylesheet" href="resources/css/plugin/datepicker/bootstrap-datepicker.css">

    <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.ko.min.js" integrity="sha512-L4qpL1ZotXZLLe8Oo0ZyHrj/SweV7CieswUODAAPN/tnqN3PA1P+4qPu5vIryNor6HQ5o22NujIcAZIfyVXwbQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
   <style>
        .container-fluid, h1, h3, h4, h5, .btn.btn-primary {
            font-family: 'Jua', sans-serif;
        }
        .container-fluid {
            color: whitesmoke;
        }
        footer {
            background-color: #0E207F;
            color: white;
            padding: 1em;
            bottom:0;
        }
        span, .nav-link {
            font-size: 1.3em;
            color: white;
        }

        p, form {
            font-family: 'Poor Story', cursive;
        }

    </style>

    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% block style %}
    {% endblock %}
</head>
<body>
    {% load socialaccount %}

    <nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: #0E207F !important;">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'bilyeo:index' %}" style="font-size: 1.7em; color: white">BILYEO</a>
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <span class="navbar-text">
                    {{ request.user.username }}님, 환영합니다.
                </span>

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    카테고리
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <li><a class="dropdown-item" href="/stuff/category/no-category/">미분류</a></li>
                      {% for category in category_list %}
                        <li><a class="dropdown-item" href="{{category.get_absolute_url}}">{{category.name}}</a></li>
                      {% endfor %}
                  </ul>
                </li>


                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    물건 관리
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url 'bilyeo:stuff_create' %}">물건 등록</a></li>
                    <li><a class="dropdown-item" href="{% url 'bilyeo:stuff_list' %}">모든 물건</a></li>
                    <li><a class="dropdown-item" href="{% url 'bilyeo:my_stuff_list' %}">내 물건 목록</a></li>
                  </ul>
                </li>

                <a class="nav-link" href="{% url 'bilyeo:my_rental_list' %}">대여 목록</a>
                <a class="nav-link" href="/accounts/logout">로그아웃</a>
                {% else %}
                <a class="nav-link" href="{% provider_login_url 'google' %}">로그인</a>
                {% endif %}
            </div>
        </div>
      </div>
    </nav>


    <center>
    {% block content %}
    {% endblock %}

        </br></br></br>

    <!-- footer -->
    <footer class="container-fluid fixed-bottom">
      <p>@Copyright myunbongs</p>
    </footer>

    </center>
    {% block scripts %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

bilyeo/templates/bilyeo/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Main{% endblock %}

{% block content %}
    <img style="max-width: 100%;height: auto; display: block;" src="{% static 'bilyeo/index.png' %}">

    </br>
    <div class='container'>
        <div class="row row-cols-6">
            {%  for stuff in stuff_list %}
            <div class="col">
                <div class="card" style="width: 18rem;">
                  <img src ="{{ stuff.image.url }}" alt = "{{ stuff.image }}">
                  <div class="card-body">
                    <h5 class="card-title">{{ stuff.name }}</h5>
                    <p class="card-text">{{ stuff.desc |truncatechars:30 }}</p>
                    <a href="{% url 'bilyeo:stuff_detail' pk=stuff.pk %}" class="btn btn-primary" style="background-color: #0E207F">대여하기</a>
                  </div>
                </div>
            <br/>
            </div>
            {% endfor %}
        </div>
    </div>

    <br/>
{% endblock %}

bilyeo/templates/bilyeo/my_rental_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}My Rental List{% endblock %}

{% block content %}
    <br/>
    <div class='container'>
        <div class="row row-cols-6">
            {%  for my_rental in my_rental_list %}
            <div class="col">
                <div class="card" style="width: 18rem;">
                  <img src ="{{ my_rental.stuff.image.url }}" alt = "{{ my_rental.stuff.image }}">
                  <div class="card-body">
                    <h5 class="card-title">{{ my_rental.stuff.name }}</h5>
                    <p class="card-text">{{ my_rental.stuff.desc |truncatechars:30 }}</p>
                    <a href="{% url 'bilyeo:rental_detail' pk=my_rental.pk %}" class="btn btn-primary" style="background-color: #0E207F">자세히 보기</a>
                  </div>
                </div>
            <br/>
            </div>
            {% endfor %}
        </div>
    </div>

    <br/>
{% endblock %}

bilyeo/templates/bilyeo/my_stuff_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}My Stuff List{% endblock %}

{% block content %}
    <br/>
    <div class='container'>
        <div class="row row-cols-6">
            {%  for my_stuff in my_stuff_list %}
            <div class="col">
                <div class="card" style="width: 18rem;">
                  <img src ="{{ my_stuff.image.url }}" alt = "{{ my_stuff.image }}">
                  <div class="card-body">
                    <h5 class="card-title">{{ my_stuff.name }}</h5>
                    <p class="card-text">{{ my_stuff.desc |truncatechars:30 }}</p>
                    <a href="{% url 'bilyeo:stuff_detail' pk=my_stuff.pk %}" class="btn btn-primary" style="background-color: #0E207F">자세히 보기</a>
                  </div>
                </div>
            <br/>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

bilyeo/templates/bilyeo/rental_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Rental Detail{% endblock %}

{% block style %}
<style>
</style>
{% endblock %}

{% block content %}
    </br>
    <h1>Rental Detail</h1>
    <hr/>
    <div class="container">
      <div class="row">
          <div class="col">
            {% if rental.stuff.image %}
                <img src ="{{ rental.stuff.image.url }}" alt = "{{ stuff.image}}" width="400em">
            {% endif %}

          </div>
          <div class="col">
            <h3>제품명: {{ rental.stuff.name }}</h3>
              <hr/>
            <p>작성자: {{ rental.stuff.author.username }}</p>
            <p>대여자: {{ rental.user.username }}</p>

            <p>대여일자: {{ rental.rental_date }}</p>
            <p>반납일자: {{ rental.return_date }}</p>

            <p>총액: {{ rental.total_fee }}원</p>
            <p>상태: {{ rental.get_status_display }}</p>

            <p>내용: {{ rental.stuff.desc }}</p>

    {% if rental.stuff.author == request.user %}
              <hr />

      <form action="" method="POST">
          {{ form | crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary mb-3" style="background-color: #0E207F">상태 변경</button>
      </form>
    {% endif %}

    {% if rental.user == request.user %}
              <hr/>
          <a href="{% url 'bilyeo:rental_update' pk=rental.pk %}" class="btn btn-primary" style="background-color: #0E207F">수정하기</a>
          <a href="{% url 'bilyeo:rental_delete' pk=rental.pk %}" class="btn btn-primary" style="background-color: red">삭제하기</a>
    {% endif %}

          </div>
      </div>
    </div>

</br>
{% endblock %}

bilyeo/templates/bilyeo/rental_filter_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Stuff List{% endblock %}

{% block content %}
    <br/>
    <h1>
        Bilyeo {% if category %} in category {{category}} {%endif%}
    </h1>
    <hr/>
    <div class='container'>
        <div class="row row-cols-6">
            {%  for stuff in stuff_list %}
            <div class="col">
                <div class="card" style="width: 18rem;">
                  <img src ="{{ stuff.image.url }}" alt = "{{ stuff.image }}">
                  <div class="card-body">
                    <h5 class="card-title">{{ stuff.name }}</h5>
                    <p class="card-text">{{ stuff.desc |truncatechars:30 }}</p>
                    <a href="{% url 'bilyeo:stuff_detail' pk=stuff.pk %}" class="btn btn-primary" style="background-color: #0E207F">대여하기</a>
                  </div>
                </div>
            <br/>
            </div>
            {% endfor %}
        </div>
    </div>

    <br/>
{% endblock %}

bilyeo/templates/bilyeo/rental_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Stuff List{% endblock %}

{% block content %}

    <br/>
    <div class='container'>
        <div class="row row-cols-6">
            {%  for stuff in stuff_list %}
            <div class="col">
                <div class="card" style="width: 18rem;">
                  <img src ="{{ stuff.image.url }}" alt = "{{ stuff.image }}">
                  <div class="card-body">
                    <h5 class="card-title">{{ stuff.name }}</h5>
                    <p class="card-text">{{ stuff.desc |truncatechars:30 }}</p>
                    <a href="{% url 'bilyeo:stuff_detail' pk=stuff.pk %}" class="btn btn-primary" style="background-color: #0E207F">대여하기</a>
                  </div>
                </div>
            <br/>
            </div>
            {% endfor %}
        </div>
    </div>

    <br/>
{% endblock %}

bilyeo/templates/bilyeo/stuff_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Stuff Detail{% endblock %}

{% block content %}
    </br>

    <h1>Stuff Detail</h1>
    <hr/>
    <div class="container">
      <div class="row">
          <div class="col">
            {% if stuff.image %}
              <img src ="{{ stuff.image.url }}" alt = "{{ stuff.image }}" width="400em">
            {% endif %}
          </div>
          <div class="col">

            <h3>제품명: {{ stuff.name }}</h3>
              <hr/>
            <p>작성자: {{ stuff.author.username }}</p>
            <p>가격: {{ stuff.fee }}</p>
            <p>내용: {{ stuff.desc }}</p>

              <hr/>

              {% if stuff.author != request.user %}
          <form id="booking-form" action="" method="POST">
              {% csrf_token %}
              <div class="input-div">
                        <label for="id_rental_date">대여일 : </label>
                        <input type="datetime-local" id="id_rental_date" name="rental_date">
                    </div>

                    <!-- Input Div -->
                    <div class="input-div">
                        <label for="id_return_date">반납일 : </label>
                        <input type="datetime-local" id="id_return_date" name="return_date">
                    </div>

              <div class="input-div">
              <button type="submit" class="btn btn-primary mb-3" style="background-color: #0E207F">빌리기</button>
              </div>
          </form>
              {% endif %}

              <hr/>
              <p>생성 시각: {{ stuff.created_at }}</p>
              <p>수정 시각: {{ stuff.updated_at }}</p>

            {% if stuff.author == request.user %}
                      <hr/>
                  <a href="{% url 'bilyeo:stuff_update' pk=stuff.pk %}" class="btn btn-primary" style="background-color: #0E207F">수정하기</a>
                  <a href="{% url 'bilyeo:stuff_delete' pk=stuff.pk %}" class="btn btn-primary" style="background-color: red">삭제하기</a>
            {% endif %}

          </div>
      </div>
    </div>

{% endblock %}