account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from account.views import signup

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', signup, name='signup'),
]

bilyeo/urls.py
from django.urls import path

from .views import StuffList, RentalList, StuffDetailView, RentalDetailView, StuffCreateView, \
    MyRentalListView, MyStuffListView, index, categories_posts, StuffUpdateView, StuffDeleteView, RentalDeleteView, \
    RentalUpdateView, RequestRentalList

app_name = 'bilyeo'

urlpatterns = [
    path('', index, name='index'),
    path('stuff_list/', StuffList.as_view(), name='stuff_list'),
    path('stuff/create/', StuffCreateView.as_view(), name='stuff_create'),
    path('stuff/<int:pk>/', StuffDetailView.as_view(), name='stuff_detail'),
    path('stuff/<int:pk>/update/', StuffUpdateView.as_view(), name='stuff_update'),
    path('stuff/<int:pk>/delete/', StuffDeleteView, name='stuff_delete'),
    path('stuff/category/<str:slug>/', categories_posts, name='category_list'),
    path('rental/<int:pk>/', RentalDetailView.as_view(), name='rental_detail'),
    path('rental/<int:pk>/delete/', RentalDeleteView, name='rental_delete'),
    path('rental/<int:pk>/update/', RentalUpdateView.as_view(), name='rental_update'),
    path('rental_list/', RentalList.as_view(), name='rental_list'),
    path('request_list/', RequestRentalList.as_view(), name='request_list'),
    path('my_rental_list/', MyRentalListView.as_view(), name='my_rental_list'),
    path('my_stuff_list/', MyStuffListView.as_view(), name='my_stuff_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bilyeo.urls')),
    path('account/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('google/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Jua&family=Poor+Story&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" >
    <link rel="stylesheet" href="resources/css/plugin/datepicker/bootstrap-datepicker.css">

    <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.ko.min.js" integrity="sha512-L4qpL1ZotXZLLe8Oo0ZyHrj/SweV7CieswUODAAPN/tnqN3PA1P+4qPu5vIryNor6HQ5o22NujIcAZIfyVXwbQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <title>
        {% block title %}
        {% endblock %}
    </title>


    <style>
        .container-fluid, h1, h3, h4, h5, .btn.btn-primary {
            font-family: 'Jua', sans-serif;
        }
        .container-fluid {
            color: whitesmoke;
        }
        footer {
            background-color: #0E207F;
            color: white;
            padding: 1em;
            bottom:0;
        }
        span, .nav-link {
            font-size: 1.3em;
            color: white;
        }

        p, form {
            font-family: 'Poor Story', cursive;
        }

    </style>

    {% block style %}
    {% endblock %}
</head>
<body>
    {% load socialaccount %}

    <nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: #0E207F !important;">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'bilyeo:index' %}" style="font-size: 1.7em; color: white">BILYEO</a>
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <span class="navbar-text">
                    {{ request.user.username }}님, 환영합니다.
                </span>

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    카테고리
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <li><a class="dropdown-item" href="/stuff/category/no-category/">미분류</a></li>
                      {% for category in category_list %}
                        <li><a class="dropdown-item" href="{{category.get_absolute_url}}">{{category.name}}</a></li>
                      {% endfor %}
                  </ul>
                </li>


                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    물건 관리
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url 'bilyeo:stuff_create' %}">물건 등록</a></li>
                    <li><a class="dropdown-item" href="{% url 'bilyeo:stuff_list' %}">모든 물건</a></li>
                    <li><a class="dropdown-item" href="{% url 'bilyeo:my_stuff_list' %}">내 물건 목록</a></li>
                  </ul>
                </li>

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    대여 관리
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url 'bilyeo:my_rental_list' %}">대여 목록</a></li>
                      <li><a class="dropdown-item" href="{% url 'bilyeo:request_list' %}">요청 목록</a></li>
                  </ul>
                </li>

                <a class="nav-link" href="{% url 'account:logout' %}">로그아웃</a>
                {% else %}
                <a class="nav-link" href="{% url 'account:signup' %}">회원가입</a>
                <a class="nav-link" href="{% url 'account:login' %}">로그인</a>
                <a class="nav-link" href="{% provider_login_url 'google' %}">구글 로그인</a><br>
                {% endif %}
            </div>
        </div>
      </div>
    </nav>


    <center>
    {% block content %}
    {% endblock %}

        </br></br></br>

    <!-- footer -->
    <footer class="container-fluid fixed-bottom">
      <p>@Copyright myunbongs</p>
    </footer>

    </center>
    {% block scripts %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>